In [1]:
a = [1,2,3]

In [2]:
a

[1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
import numpy as np
b = np.array(a)

In [5]:
b

array([1, 2, 3])

In [6]:
b + b

array([2, 4, 6])

In [7]:
b + 1

array([2, 3, 4])

In [8]:
b**2

array([1, 4, 9])

In [9]:
np.sin(b)

array([0.84147098, 0.90929743, 0.14112001])

In [10]:
range(5)

range(0, 5)

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
b = np.linspace(0, 5, 11)

In [17]:
len(b)

11

In [18]:
a

[1, 2, 3]

In [19]:
aa = [x + y for x,y in zip(a,a)]

In [20]:
aa

[2, 4, 6]

In [21]:
bb = b + b

In [22]:
bb

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
b = np.array(a)

In [24]:
bb = b + b

In [25]:
bb

array([2, 4, 6])

In [26]:
a = range(10000)

In [27]:
%timeit aa = [x + y for x,y in zip(a,a)]

705 μs ± 29.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
b = np.array(a)

In [29]:
%timeit bb = b + b

6.64 μs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
2.16e-3/65.2e-6

33.128834355828225

In [31]:
705/6.64

106.17469879518073