In [2]:
a = [1,2,3]

In [3]:
a

[1, 2, 3]

In [4]:
a + a

[1, 2, 3, 1, 2, 3]

In [6]:
import numpy as np
b = np.array(a)

In [7]:
b

array([1, 2, 3])

In [8]:
b + b

array([2, 4, 6])

In [9]:
b + 1

array([2, 3, 4])

In [10]:
b**2

array([1, 4, 9])

In [11]:
np.sin(b)

array([0.84147098, 0.90929743, 0.14112001])

In [18]:
range(5)

range(0, 5)

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
b = np.linspace(0, 5, 11)

In [21]:
len(b)

11

In [22]:
a

[1, 2, 3]

In [23]:
aa = [x + y for x,y in zip(a,a)]

In [24]:
aa

[2, 4, 6]

In [26]:
bb = b + b

In [27]:
bb

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
b = np.array(a)

In [29]:
bb = b + b

In [30]:
bb

array([2, 4, 6])

In [31]:
a = range(10000)

In [32]:
%timeit aa = [x + y for x,y in zip(a,a)]

983 μs ± 78 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [34]:
b = np.array(a)

In [35]:
%timeit bb = b + b

13.1 μs ± 5.71 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [36]:
2.16e-3/65.2e-6

33.128834355828225

In [37]:
983/13.1

75.0381679389313